### ISSUE TITLE
Minor Bug: Secrets Manager CLI List

### ISSUE THREAD

**Issue by wolfrex2809** [Excoriate/terraform-registry-aws-storage#1]
## Describe the Bug
When we execute the following command, `task secrets-manager-cli -- list --region={Region}`, it brings only the `Secrets` that have a set value. It means that if we got a Secret with no value will not be listed.

Note: It could be a problem when we create a Secret via `CLI` with no value, and we need to get the `Name` of the created `Secret`.

## Steps to Reproduce
1. Go to repo root directory
2. Run `task secrets-manager-cli -- list --region={Region}`

**Comment by Excoriate** [comment]
Isn't an issue. It was tested in `int`
